apiVersion: v1
data:
  unbound.conf: |-
    server:
      verbosity: 1
      val-log-level: 2
      interface: 0.0.0.0
      access-control: 10.0.0.0/8 allow
      access-control: 172.16.0.0/12 allow
      msg-cache-size: 200m
      rrset-cache-size: 400m
      hide-identity: yes
      hide-version: yes
      auto-trust-anchor-file: "/etc/unbound/root.key"
      num-threads: 8
      use-syslog: no
      harden-dnssec-stripped: no
      username: ""
      outgoing-range: 950
      num-queries-per-thread: 512

      # Reduce lock contention
      msg-cache-slabs: 8
      key-cache-slabs: 8
      infra-cache-slabs: 8
      rrset-cache-slabs: 8

      edns-buffer-size: 1480

      # Do both UDP and TCP
      do-udp: yes
      do-tcp: yes

      # Protect against weirdly sized queries
      harden-short-bufsize: yes
      harden-large-queries: yes

      # Harden against common attacks
      harden-glue: yes
      harden-algo-downgrade: yes

      # Prefetch records when about to expire
      prefetch: yes
      prefetch-key: yes

      # Respect round robin
      rrset-roundrobin: yes

      # Minimal responses to save network traffic
      minimal-responses: yes


      # Add local zone for Cisco wireless controller
      local-zone: "CISCO-CAPWAP-CONTROLLER.npf." static
      local-data: "CISCO-CAPWAP-CONTROLLER.npf. IN A 10.0.1.11"

      # Mark domains as insecure to serve as local zones
      domain-insecure: "npf."
      domain-insecure: "cluster.local."
      private-domain: "npf."
      private-domain: "cluster.local."

    # Enable remote control for metrics
    remote-control:
      control-enable: yes
      control-interface: 0.0.0.0
      control-port: 8953
      control-use-cert: yes

    stub-zone:
      name: "cluster.local."
      stub-addr: 10.96.0.10

    stub-zone:
      name: "npf."
      stub-addr: 10.96.5.3@5353

    forward-zone:
      name: "."
      forward-addr: 8.8.8.8
      forward-addr: 8.8.4.4
      forward-first: yes

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: unbound
  namespace: dns