apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: dns
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: unbound
    namespace: dns
  spec:
    replicas: 2
    template:
      metadata:
        labels:
          app: unbound
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                      - unbound
                topologyKey: "kubernetes.io/hostname"
        containers:
        - name: unbound
          image: npflan/unbound:2.5
          args:
            - '-c'
            - '/unbound/config/unbound.conf'
          volumeMounts:
            - mountPath: /unbound/config
              name: unbound-config
          resources:
            limits:
              memory: 1000M
          livenessProbe:
            exec:
              command:
                - sh
                - -ec
                - /usr/bin/drill -4 dns.msftncsi.com @0.0.0.0 | /bin/grep 131.107.255.255 > /dev/null
            initialDelaySeconds: 1
            timeoutSeconds: 1
            periodSeconds: 3
          readinessProbe:
            exec:
              command:
                - sh
                - -ec
                - /usr/bin/drill -4 dns.msftncsi.com @0.0.0.0 | /bin/grep 131.107.255.255 > /dev/null
            initialDelaySeconds: 1
            timeoutSeconds: 1
            periodSeconds: 3
          ports:
            - containerPort: 8953

        - name: unbound-exporter
          image: npflan/unbound_exporter:0.5
          volumeMounts:
            - mountPath: /unbound/config
              name: unbound-config
          resources:
            limits:
              memory: 512M

        volumes:
          - name: unbound-config
            configMap:
              name: unbound
              items:
              - key: unbound.conf
                path: unbound.conf
- kind: Service
  apiVersion: v1
  metadata:
    name: unbound
    namespace: dns
  spec:
    clusterIP: 10.96.5.1
    selector:
      app: unbound
    ports:
      - name: dns-tcp
        port: 53
        protocol: TCP
        targetPort: 53
      - name: dns-udp
        port: 53
        protocol: UDP
        targetPort: 53
      - name: dns-metrics
        port: 9167
        protocol: TCP
        targetPort: 9167
      #- name: unbound-control-tcp
      #  port: 8953
      #  protocol: TCP
      #  targetPort: 8953
      #- name: unbound-control-udp
      #  port: 8953
      #  protocol: UDP
      #  targetPort: 8953