apiVersion: v1
data:
  named.conf: |
    options {
        directory "/var/named";
        pid-file "/run/named/named.pid";
        listen-on-v6 { none; };
        listen-on port 5353 { any; };
        allow-recursion { none; };
        allow-transfer { none; };
        allow-update { none; };
        version none;
        hostname none;
        server-id none;
    };

    zone "npf" IN {
        type master;
        file "/bind/config/npf.zone";
        allow-update { none; };
    };

    zone "255.10.in-addr.arpa" IN {
        type master;
        file "/bind/config/255.10.in-addr.arpa.zone";
    };
    zone "168.192.in-addr.arpa" IN {
        type master;
        file "/bind/config/168.192.in-addr.arpa.zone";
    };

  npf.zone: |
    $ORIGIN npf.
    $TTL 600

    @	IN	SOA	ns1.npf.	hostmaster.npf. (
        2020101004 ; Serial
        300 ; Refresh
        150 ; Retry
        600 ; Expire
        600) ; Minimum

        IN	NS	ns1.npf.

    ns1				IN	A	10.96.5.3
    dash IN CNAME grafana.grafana.svc.cluster.local.
    prom IN CNAME prometheus-server.prometheus.svc.cluster.local.
    alert IN CNAME prometheus-alertmanager.prometheus.svc.cluster.local.
    shinobi IN CNAME shinobi.shinobi.svc.cluster.local.
    heatmap IN CNAME sw-heatmap.sw-heatmap.svc.cluster.local.
    gaas IN CNAME gaas-portal.gaas.svc.cluster.local.
    shutdown IN CNAME shutdown-svc.cisco.svc.cluster.local.
    argo IN CNAME argocd-server.argocd.svc.cluster.local.
    gaas-api IN CNAME gaas-api-service.gaas.svc.cluster.local.
    rtmp IN CNAME rtmp.rtmp.svc.cluster.local.

    avatar IN A 10.0.0.1
    leviathan IN A 10.0.0.5
    ragnarok IN A 10.0.0.9
    erebus IN A 10.0.0.13
    kubectl IN A 172.20.11.102
    chimera IN A 172.20.11.104
    archon IN A 172.20.22.104

    $ORIGIN access.npf.
    e1-ab2 IN A 10.255.254.13
    e1-ac1 IN A 10.255.254.14
    e1-ad1 IN A 10.255.254.16
    e1-ad2 IN A 10.255.254.17
    e1-ae1 IN A 10.255.254.18
    e1-ae1 IN A 10.255.254.19
    d13-af2 IN A 10.255.254.21
    isp2 IN A 10.255.254.200

    telemetry IN SRV 0 0 9167 e1-ab2.access.npf.
    telemetry IN SRV 0 0 9167 e1-ac1.access.npf.
    telemetry IN SRV 0 0 9167 e1-ad1.access.npf.
    telemetry IN SRV 0 0 9167 e1-ad2.access.npf.
    telemetry IN SRV 0 0 9167 e1-ae1.access.npf.
    telemetry IN SRV 0 0 9167 e1-ae1.access.npf.
    telemetry IN SRV 0 0 9167 d13-af2.access.npf.
    telemetry IN SRV 0 0 9167 isp2.access.npf.

    $ORIGIN dist.npf.
    c1 IN A 10.255.255.1
    c2 IN A 10.255.255.2
    isp IN A 10.255.254.250
    telemetry IN SRV 0 0 9167 c1.dist.npf.
    telemetry IN SRV 0 0 9167 c2.dist.npf.
    telemetry IN SRV 0 0 9167 isp.dist.npf.

    $ORIGIN link.npf.
    te1-8.e1 IN A 192.168.255.161
    te1-1.e1 IN A 192.168.255.178
    te1-2.e1 IN A 192.168.255.182
    te1-3.e1 IN A 192.168.255.186
    te1-4.e1 IN A 192.168.255.190


  255.10.in-addr.arpa.zone: |
    $ORIGIN 255.10.in-addr.arpa.
    $TTL 600

    @	IN	SOA	ns1.npf.	hostmaster.npf. (
        2020101001 ; Serial
        300 ; Refresh
        150 ; Retry
        600 ; Expire
        600) ; Minimum

        IN	NS	ns1.npf.

    13.254 IN PTR e1-ab2.access.npf
    14.254 IN PTR e1-ac1.access.npf
    16.254 IN PTR e1-ad1.access.npf
    17.254 IN PTR e1-ad2.access.npf
    18.254 IN PTR e1-ae1.access.npf
    19.254 IN PTR e1-ae1.access.npf
    21.254 IN PTR d13-af2.access.npf
    200.254 IN PTR isp2.access.npf
    250.254 IN PTR isp.dist.npf
    1.255 IN PTR c1.dist.npf.
    2.255 IN PTR c2.dist.npf.

  168.192.in-addr.arpa.zone: |
    $ORIGIN 168.192.in-addr.arpa.
    $TTL 600

    @	IN	SOA	ns1.npf.	hostmaster.npf. (
        2020101001 ; Serial
        300 ; Refresh
        150 ; Retry
        600 ; Expire
        600) ; Minimum

        IN	NS	ns1.npf.

    161.255 IN PTR te1-8.e1.link.npf
    178.255 IN PTR te1-1.e1.link.npf
    182.255 IN PTR te1-2.e1.link.npf
    186.255 IN PTR te1-3.e1.link.npf
    190.255 IN PTR te1-4.e1.link.npf



kind: ConfigMap
metadata:
  creationTimestamp: null
  name: bind
  namespace: dns
